
# %% [markdown]
# # Find out which regional models the Flamish "Grondwatersimulator" heeft.
#
# W A R N I N G
#
# This file has been run and should not be run again. It takes along time because it
# runs modflow for all regional models in all projects to generate the .grb (binary
# grid files) which were absent in the originally obtained files (due to option NOGRB
# in one of the Modflow input files.)
#
# The zipfiles contains folders, one per case or project, with subfolders specifying
# the preparation and the actual files to run a regional and local Modflow 6 model
# (with quadtree mesh). The userinfo.json file in the directory input specifies the
# intervention that is modelled.
#
# The regional models are from the Flamish "Grondwatersimiulator"
#
# Each project or case folder constains two models:
#
# * regional (the regional model)
# * model (the local model)
#
# The goal is to uncover the regional model, see how many there are, what
# area they cover and what their layers are and their properties.
#
# A way to uncover the regional models is to show the contour of the model grid
# of the regional models. However these grids have to be generated by running
# Modflow itself as they are not in the regional folders. The reason is that
# the .disv files had the NOGRB option. I removed these and ran modflow
# which caused the grb files to be generated.
# 
# The result is that every project has it's own regioinal .grb file after running
# this script.
# 
# in the folder regional.
# The local model in the directory model already
# have their .grb file.
# TO 2025-10-24


# %% 
import os
from flopy.mf6 import MFSimulation
from glob import glob

# %%
def run_sim_to_generate_regional_model_grid_file(project_name):
    """Return nothing but generate .grb files for regional models of all projects.
    
    Parameters
    ----------
    project_name: str (fname) like "Rapport LC_212_filterbemaling"
        name of the project main directory
    """
    # --- get the projects' retional model's folder
    model_folder = os.path.join(prj_folder, project_name, "regional")
    assert os.path.isdir(model_folder)

    # --- get the .disv file
    disv_path = os.path.join(model_folder, "no_permits.disv")
    assert os.path.isfile(disv_path), f"No file <{disv_path}>"

    # --- get the simulation (Path to folder containing the .nam file)
    sim = MFSimulation.load(sim_ws=model_folder)

    # -- in case we need the grid without a grb file
    # Retrieve the first groundwater flow model
    # model = sim.get_model(list(sim.model_names)[0])
    # modelgrid = model.modelgrid

    sim.write_simulation()

    # -- remove the NOGRB option to make sure mf6 generates the .grb file
    with open(disv_path, "r") as f:
        lines = f.readlines()

    with open(disv_path, "w") as f:
        for line in lines:
            if "NOGRB" not in line.strip():
                f.write(line)

    # --- run mf6 to generated the .grb file and show that it does so
    print(f"Running regional model for <{project_name}>")
    success, buff = sim.run_simulation()
    if not success:
        raise RuntimeError(f"MODFLOW 6 failed to run for project {project_name}")
    else:
        grb_path = disv_path.replace(".disv", ".disv.grb")
        print(f"Grb file exists: {os.path.isfile(grb_path)}")
        print(f"Done <{project_name}>")
    return None


# %% Takes a long time to do, has been run should not be run again.

# -- get the prj_folder
try:
    prj_folder = os.path.join(os.getcwd(), '../data', '6194_GWS_testen')
    assert os.path.isdir(prj_folder), f"Path not found <{prj_folder}>"
except Exception as e:
    prj_folder = os.path.join(os.getcwd(), 'data', '6194_GWS_testen')
    assert os.path.isdir(prj_folder), f"Path not found <{prj_folder}>"

# --- all the zip files. One per project
pr_names = glob(prj_folder + '/*.zip')

# --- remove .zip to get the project directory names
# --- each of which is an expanded zip file
pr_names = [p.replace('.zip', '') for p in pr_names]

# --- Run modflow for each project directory in order to generate the
# --- .grb file in the regional directory
for pr_name in pr_names:
    run_sim_to_generate_regional_model_grid_file(pr_name)
    
# %%
